THP_eval:
  base_config:
    backend: torch
    base_dir: ./checkpoints_thp/
    dataset_id: amazon
    model_id: THP
    runner_id: std_tpp
    stage: eval
  model_config:
    dropout: 0.1
    hidden_size: 64
    num_heads: 2
    num_layers: 2
    pretrained_model_dir: ./checkpoints_thp/XXXXX/models/saved_model
    thinning:
      dtime_max: 10
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1
      num_samples_boundary: 5
      num_seq: 10
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 16
    use_ln: false
  trainer_config:
    batch_size: 256
    gpu: -1
    max_epoch: 1
    metrics:
    - acc
    - rmse
    seed: 2019
THP_train:
  base_config:
    backend: torch
    base_dir: ./checkpoints_thp/
    dataset_id: amazon
    model_id: THP
    runner_id: std_tpp
    stage: train
  model_config:
    dropout: 0.1
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    mc_num_sample_per_step: 20
    num_heads: 2
    num_layers: 2
    thinning:
      dtime_max: 10
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 16
    use_ln: false
  trainer_config:
    batch_size: 256
    gpu: -1
    learning_rate: 0.001
    max_epoch: 10
    metrics:
    - acc
    - rmse
    optimizer: adam
    seed: 2019
    shuffle: false
    use_tfb: false
    valid_freq: 1
data:
  amazon:
    data_format: json
    data_specs:
      max_len: 100
      num_event_types: 16
      pad_token_id: 16
      padding_side: right
      truncation_side: right
    test_dir: easytpp/amazon
    train_dir: easytpp/amazon
    valid_dir: easytpp/amazon
pipeline_config_id: runner_config
