data_config:
  train_dir: ./data/stackoverflow/train.pkl
  valid_dir: ./data/stackoverflow/dev.pkl
  test_dir: ./data/stackoverflow/test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 10
    pad_token_id: 10
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: 200
base_config:
  stage: train
  backend: torch
  dataset_id: stackoverflow
  runner_id: std_tpp
  model_id: THP
  base_dir: ./checkpoints_stackoverflow/
  specs:
    log_folder: ./checkpoints_stackoverflow/34541_140704456446144_251113-085126
    saved_model_dir: ./checkpoints_stackoverflow/34541_140704456446144_251113-085126/models/saved_model
    saved_log_dir: ./checkpoints_stackoverflow/34541_140704456446144_251113-085126/log
    output_config_dir: ./checkpoints_stackoverflow/34541_140704456446144_251113-085126/THP_train_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 64
  time_emb_size: 16
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning: null
  num_event_types_pad: 11
  num_event_types: 10
  event_pad_index: 10
  model_id: THP
  pretrained_model_dir: null
  gpu: -1
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: -1
  batch_size: 256
  max_epoch: 10
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
